authentication_system
BahaBoualii/leftover pull request #1
Opened 2024-11-18 11:03 UTC by mahaabid2001

2024-11-18 18:06 UTC, BahaBoualii commented on src/authentification/auth.service.ts
> +      console.log('USer:', user);
delete this console.log

2024-11-18 18:06 UTC, BahaBoualii commented on src/authentification/auth.service.ts
> +      console.log(error);
change this to console.error

2024-11-18 18:06 UTC, BahaBoualii commented on src/authentification/auth.service.ts
> +      console.log(error);
change this to console.error

2024-11-18 18:06 UTC, BahaBoualii commented on src/authentification/guards/jwt-auth.guard.ts
> +    console.log(user);
delete this console.log

2024-11-18 18:06 UTC, BahaBoualii commented on src/mailing/mail.service.ts
> +      service: 'gmail',
I guess we need to change this to support multiple services, what do you think?

2024-11-18 18:06 UTC, BahaBoualii commented on src/mailing/mail.service.ts
> +    console.log(verificationUrl);
delete this

2024-11-18 18:06 UTC, BahaBoualii commented on src/mailing/mail.service.ts
> +    console.log(resetUrl);
delete this

2024-11-18 18:06 UTC, BahaBoualii commented on src/users/user.controller.ts
> +        throw new ForbiddenException('User not found');
change the exception type to NotFound

2024-11-18 18:06 UTC, BahaBoualii commented on src/users/user.controller.ts
> +      console.log(error)
change to console.error

2024-11-18 18:06 UTC, BahaBoualii commented on src/users/user.controller.ts
> +      return users.map(
we can use the select inside the findAll instead of the map

2024-11-18 18:06 UTC, BahaBoualii commented on src/users/user.controller.ts
> +        throw new ForbiddenException('User not found');
change the exception type to NotFound

2024-11-18 18:06 UTC, BahaBoualii commented on src/users/user.controller.ts
> +      const { password, resetToken, resetTokenExpiry, ...result } = user;
we can use the select option inside of findById instead of this

2024-11-18 18:06 UTC, BahaBoualii commented on src/mailing/mail.service.ts
> +    console.log(resetUrl);
delete this

2024-11-18 22:04 UTC, mahaabid2001 commented on src/mailing/mail.service.ts
> +      service: 'gmail',
not top priority right now, but we could consider that in future.

2024-11-19 18:24 UTC, BahaBoualii requested changes

2024-11-19 18:24 UTC, BahaBoualii commented on src/users/user.controller.ts
> +      }
this should be integrated in the method defined in the service

2024-11-19 18:24 UTC, BahaBoualii commented on src/users/user.controller.ts
> +      return users;
we can just replace this with return await this.userService.findAll():

2024-11-19 19:31 UTC, BahaBoualii approved these changes

2024-11-19 19:34 UTC, merged